site_name: Native Cursor
site_url: https://gameobject.xyz/nativecursor/
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - codehilite
theme: material